apiVersion: apps/v1
kind: Deployment
metadata:
  name: artic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artic-bot
  template:
    metadata:
      labels:
        app: artic-bot
    spec:
      containers:
        - name: bot
          image: ghcr.io/week-book/artic-telegram-bot:sha-3045ae5aa3342ab0536d696427952c9fbe046d5e
          imagePullPolicy: IfNotPresent
