apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - secrets/artic-bot-sealed.yaml
images:
  - name: ghcr.io/week-book/artic-telegram-bot
    newTag: sha-1298d0d1b8bec4758e0f6b74e0a113aa7c141c2b
